### ISSUE TITLE
Die arrangement and pins documentation change.

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel#104]
[[caravel](https://github.com/efabless/caravel)/[docs](https://github.com/efabless/caravel/tree/main/docs)/[source](https://github.com/efabless/caravel/tree/main/docs/source)/supplementary-figures.rst](https://github.com/efabless/caravel/blob/main/docs/source/_static/die_pads.svg)

The diagram for Die arrangement and pins indicates that `mprj_io[0:7]` have fixed defaults but the actual `scripts/gen_gpio_defaults.py` only has fixed values for `mprj_io[0:4]`.

**Comment by DavidRLindley** [comment]
This is old and stale.  I'm closing.  We can reopen if still an issue.
