### ISSUE TITLE
pwr_ctrl_out register doesn't have reset value

### ISSUE THREAD

**Issue by M0stafaRady** [efabless/caravel#106]
register `pwr_ctrl_out` inside `housekeeping.v` is always undefined because the register never gets reset. 

possible solution is to add:

```
if (porb == 1'b0) begin
            ...
            ...
            ...
         pwr_ctrl_out <= `MPRJ_PWR_PADS'h0;
```

**Comment by RTimothyEdwards** [comment]
`pwr_ctrl_out` is unused and is reserved for such time as we have a known good LDO for generating the 1.8V digital supply on-chip.  The omission of an initial value has been noted and will be corrected.
