### ISSUE TITLE
Push all OpenLane log files to the repo

### ISSUE THREAD

**Issue by shalan** [efabless/caravel#118]
Push all OpenLane log files to the repo as a way to indicate what happens during physical implementation.

**Comment by shalan** [comment]
Archive the runs in a gitlab repo

**Comment by marwaneltoukhy** [comment]
Push to Gitlab [here]( https://gitlab.com/efabless/designs/caravel_mgmt_soc_litex) and [here](https://gitlab.com/efabless/designs/caravel_archive)
