### ISSUE TITLE
Enable both CTS and Optimizations for Caravel top-level

### ISSUE THREAD

**Issue by shalan** [efabless/caravel#120]

**Comment by shalan** [comment]
Caravel design does not allow top-level cells; hence, top-Level CTS is not possible.

However, top-level clock buffering using dedicated buffering macros and/or pass through clocks is undergoing.

**Comment by marwaneltoukhy** [comment]
The current Caravel implementation doesn't allow any top level CTS. However, clock signals are buffered properly to avoid any SI issues.
Caravel has to be redesigned using different hierarchy to allow top level CTS, this might be tackled in the near future.
