### ISSUE TITLE
Update `rtl/caravel.v` to reflect the ECOs done in Caravel netlist

### ISSUE THREAD

**Issue by shalan** [efabless/caravel#124]
Caravel top-level layout was ECO'ed to fix some issues including shorted GPIO_control_block clocks. The resulted in a new Caravel ECO'ed top-level netlist. `rtf/caravel.v` must be updated to reflect the ECOs; otherwise the same ECOs have to be applied every time Caravel is hardened.

**Comment by azwefabless** [comment]
Have not found the commit. Work is completed and verified in fullchip netlist.
