### ISSUE TITLE
simple_por lef view is not abstract

### ISSUE THREAD

**Issue by kareefardi** [efabless/caravel#164]

**Comment by RTimothyEdwards** [comment]
@kareefardi :  How does it differ?

**Comment by kareefardi** [comment]
I didn't not check the layout. What I know is that the gds and lef belong to different commits (which isn't necessarily an issue). However using the current lef leads to drcs during the toplevel routing which get removed upon regenerating the lef (again doesn't mean a 100% that the views aren't matching but likely they are).

**Comment by RTimothyEdwards** [comment]
I see that the LEF file is a detailed view of the layout, which it shouldn't be;  the abstract view in `maglef/` is what I would expect the LEF to look at;  obviously the `maglef/` view was generated from a different LEF file.  I should have that LEF file somewhere locally or else I can regenerate it.  I will make a pull request for it.

**Comment by kareefardi** [comment]
rename the issue to reflect the state

**Comment by RTimothyEdwards** [comment]
@kareefardi :  PR #170 should fix this problem.
