### ISSUE TITLE
Top level layout no longer has ports.

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel#171]
Ports over the pads (with visible text!) used to be part of the top level layouts but got removed somehow (how did that happen???).  The ports need to be added back.  Along with probably a dozen other things that have to be done by hand (or else have a script made to do them) on the top level.

This error prevents LVS from being run correctly.

**Comment by kareefardi** [comment]
There is a routine in the interactive script called `label_macro_pins`. As an intermediate wip step, this api wasn't used. Probably that's the cause of the issue. I will make sure to follow the interactive script to the end.

**Comment by RTimothyEdwards** [comment]
This has been verified on the Caravel top level layout.
