### ISSUE TITLE
ports missing in `chip_io` lef view

### ISSUE THREAD

**Issue by kareefardi** [efabless/caravel#174]
```
vccd
vdda1
vddio
vssa
vssa1
vssd
vssio
```
the following ports are missing from `chip_io` lef view

**Comment by RTimothyEdwards** [comment]
@kareefardi :  Some of the pin labels inside the power supply rings got erased.  I will fix them right away.

**Comment by RTimothyEdwards** [comment]
@kareefardi :  Please see PR #175, which fixes the error.
