### ISSUE TITLE
Antenna fix implementation ssue causing rework late in the integration flow

### ISSUE THREAD

**Issue by azwefabless** [efabless/caravel#185]
Antenna Flow Strategy 3 and 4 have partial solution. Need an enhancement that is an integration of both strategies with antenna diodes on input pins and also with abilit to iterate to fix detaile droute inside of the block.

**Comment by marwaneltoukhy** [comment]
One solution is to combine strategies 3 and 4, this was tested and gave very good results. More investigation to be done.
