### ISSUE TITLE
outdated mag file in `./mag`

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel#193]
There's a mgmt_core_wrapper.mag file in caravel repo, I know we used that for tapeout, but why not use what's on the [caravel_mgmt_soc_litex](https://github.com/efabless/caravel_mgmt_soc_litex) repo? That way we'll be sure that tapeout always picks up the latest mag file.

**Comment by jeffdi** [comment]
the mag file is an abstract view, but does need to be updated since the block size changed.

**Comment by azwefabless** [comment]
Requires documentation to close

**Comment by marwaneltoukhy** [comment]
closed with PR #300
