### ISSUE TITLE
32 bit counter

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/caravel#21]
32 bit timers/counters are deprecated: https://en.wikipedia.org/wiki/Year_2038_problem
32 bit timers/counters are end of life! 
Due to using a 32-bit CPU we might need an atomic way to read a 64-bit timer, which might make it a bit more complex than it should be.

**Comment by thesourcerer8** [comment]
https://sites.google.com/site/edmarkovich2/whywindows95andwindows98wouldcrashafter49.7daysofuptime

**Comment by mithro** [comment]
@thesourcerer8 -- This only affects timers/counters which store Unix timestamps?

**Comment by RTimothyEdwards** [comment]
The counter implemented on Caravel is a 64-bit counter, anyway (two 32-bit counters, chained together).

**Comment by RTimothyEdwards** [comment]
@thesourcerer8  :  Also you would never use a timer/counter as a real-time clock unless you had the circuitry to sync to a real-time pulse.

**Comment by RTimothyEdwards** [comment]
Because this describes a non-issue, it will be closed now.
