### ISSUE TITLE
generate libs for blocks that were not updated

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel#224]

**Comment by RTimothyEdwards** [comment]
Use PrimeTime

**Comment by marwaneltoukhy** [comment]
Same as #199

**Comment by jeffdi** [comment]
Complete via issue #199

**Comment by passant5** [comment]
issue #199 PR includes only the re-implemented blocks. Other blocks are still wip

**Comment by passant5** [comment]
The updated hierarchy used macros libs could be found [here](https://github.com/efabless/caravel/tree/main/lib)
