### ISSUE TITLE
Add substrate cut to gpio_control_block on gpio_logic_high to avoid LVS errors

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel#228]

**Comment by RTimothyEdwards** [comment]
Description:  The synthesis tools don't know how to create a substrate cut layer in a layout that declares multiple ground domains.  This needs to be done by hand whenever such a block is synthesized.  I intend to put this in a script, although that script will then need to be modified if the layout changes.  At least then there will be a record of what additional tasks need to be done to specific layouts in support of LVS.
