### ISSUE TITLE
newly added module flash_clkrst_buffers misses power connection

### ISSUE THREAD

**Issue by M0stafaRady** [efabless/caravel#236]
Module flash_clkrst_buffers  added to the cavel.v gatelevel by this [commit ](https://github.com/efabless/caravel/commit/6452f14de02d34ba388f6d8a162c1c05234c0505#diff-ca18a3807a48e862d85262e6f83f7cada7791f9f4b2600d04095d09d2a6d9ec0) is missing power connections and that broke the gatelevel simulation. 
The following  [PR](https://github.com/efabless/caravel/pull/235) solves this issue.

**Comment by marwaneltoukhy** [comment]
Fixed with `fc0701003cd25d765e9d65507f1c0a88b6c63f14` on `caravel_redesign`
