### ISSUE TITLE
Sparse PDN in housekeeping block

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel#282]
The housekeeping block has very sparse PDN.  This was fixed in the management SoC (power routes were doubled) but the housekeeping could use at least doubling of the number of PDN stripes.

Side note:  It appears that the PDN generator is miscounting the stripes.  Often there is one less stripe than there should be on one or two sides.  It seems like the PDN is correctly counting the space available but sometimes it doesn't draw the last stripe in.  This unfortunately causes the worst-case resistance from any cell to the power grid to be double what you would expect for the specified power stripe pitch.

**Comment by mo-hosni** [comment]
#288 
Fixed and merged.
