### ISSUE TITLE
floating input to mgmt_core_wrapper

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel#316]
The `mgmt_core_wrapper` input port, `porb_h_in`, is not connected to anything. This is input to `sky130_fd_sc_hd__clkbuf_16` and should be tied low or high (but probably not directly).

**Comment by RTimothyEdwards** [comment]
@marwaneltoukhy :  I suggest tying this input directly to its neighbor `por_l_in`.  Otherwise you have to ground it by adding a constant value output cell or grabbing such a signal from somewhere.  There is no downside to having this unused buffer path be a copy of the `por_l` signal.

**Comment by RTimothyEdwards** [comment]
Plus the direct connection can be made with a simple ECO layout change to short the two pins with a m3 wire and does not involve re-running top-level routing.
