### ISSUE TITLE
Incorrect indexes for GPIO "oeb" and "one" pins in caravan

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel#328]
The pins for GPIOs on the left hand side on caravan that do not have an independently controllable OEB line (GPIOs 25 to 34) have been indexed correctly, causing the OEB lines to be driven from pads on the right hand side, and making a mess of extremely long wires that were not intended.  Note that this configuration is _functionally_ correct because the OEBs are properly tied high.  But it's still a floorplanning nightmare and needs to be corrected.

**Comment by d-m-bailey** [comment]
did you mean "indexed **incorrectly**"?
