### ISSUE TITLE
All source documents for the PDFs should be in this repo

### ISSUE THREAD

**Issue by mithro** [efabless/caravel#4]
There are a bunch of PDFs in this repository. Please include the source files for these PDFs in the repo.

**Comment by mithro** [comment]
Looks like this might be done now?

**Comment by RTimothyEdwards** [comment]
I only had two PDFs which were created from xcircuit sources.  I incorporated the contents of one of those into the other, removed the corresponding PDF, and added the xcircuit source file.  That doesn't seem to be a "bunch of" PDFs?  Currently there should be only one.
