### ISSUE TITLE
MPW-5 Tapeout fails with FEOL DRC violations

### ISSUE THREAD

**Issue by BrandonOng22** [efabless/caravel#40]
The precheck passed successfully. Tapeout fails with 4 FEOL drc violations. The violations are 'nwell.6' in the H3_sky130_fd_io__gpiov22_amux cell. The violation occurs outside of my design.

`STDERR: [ WARN ] FEOL Check Result: 'caravel_00054489.oas' has 4 DRC violations.`

![feol_drc](https://user-images.githubusercontent.com/50957454/156427030-703a74c2-26d7-4681-b4b6-89395e08b3b5.png)

**Comment by mattvenn** [comment]
thanks, this is a known issue and it's been solved in open_pdks already. Now we are waiting on it going live on the efabless server.

**Comment by BrandonOng22** [comment]
> thanks, this is a known issue and it's been solved in open_pdks already. Now we are waiting on it going live on the efabless server.

Thanks Matt. Is this something that I should just wait until it gets updated?

**Comment by mattvenn** [comment]
Yep, I'll close this issue when it's solved.

**Comment by RTimothyEdwards** [comment]
@mattvenn :  This was solved with a "hack" for MPW-five (failing cells are ignored by klayout DRC) and the issue should remain open until the proper fix (in open_pdks) gets applied to the server;  and at that time we need to make sure that the klayout DRC hack is removed.

**Comment by RTimothyEdwards** [comment]
This was corrected a long time ago by a workaround in open_pdks:  `sky130/custom/scripts/fix_gpiov2_gds.py`.  This ticket can be closed.
