### ISSUE TITLE
add warning to docs about wishbone address limitation

### ISSUE THREAD

**Issue by mattvenn** [efabless/caravel#43]
https://github.com/efabless/caravel_mgmt_soc_litex/issues/21

very likely to go to mpw5 tapeout as well, so users need to know.

@suppamax

**Comment by mattvenn** [comment]
this should go into the management litex core instead.

**Comment by suppamax** [comment]
(Here)[https://caravel-harness.readthedocs.io/en/latest/memory-mapped-io-summary.html] a wishbone base address is mentioned: should I add a "wishbone last addr" field?

I cannot find a wishbone-related documentation in the management SoC repo (and it looks like there is no readthedocs page yet).

**Comment by mattvenn** [comment]
I closed this issue - let's discuss here: https://github.com/efabless/caravel_mgmt_soc_litex/issues/21
