### ISSUE TITLE
scripts/gen_gpio_defaults.py is not working in caravel-redesign-2

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel#438]
The script [gen_gpio_defaults.py](https://github.com/efabless/caravel/blob/caravel-redesign-2/scripts/gen_gpio_defaults.py) outputs are identical mag files of the original gpio_defaults_block.

I am working on the branch caravel-redesign-2. The original gpio_defaults_block layout was updated by me.

**Comment by RTimothyEdwards** [comment]
There were several updates that addressed this problem, but the most recent one is pull request #441 in the main branch which corrects one last error and verifies that all the resulting GPIO blocks are correct (with a script in the scripts/ directory).
