### ISSUE TITLE
Modify the HDL hierarchy of caravan to be consisting of caravan_core and chip_io_alt

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel#446]
The HDL hierarchy of `caravan` should be modified to be consisting of `caravan_core` and `chip_io_alt` so the same changes for `caravel` can be implemented.

**Comment by RTimothyEdwards** [comment]
@mo-hosni :  Whatever else you do, make absolutely sure that the digital synthesized part of `caravan_core` extends no higher than the topmost GPIO and does not cross above the top of the user project area.

**Comment by mo-hosni** [comment]
@RTimothyEdwards : Thanks for the note. I will absolutely do that.

**Comment by mo-hosni** [comment]
done in: https://github.com/efabless/caravel/pull/457
