### ISSUE TITLE
gpio_defaults_block_34 not replaced during merge.

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel#45]
The instance name in `caravel.mag` for `block_34` does not match other instances, so it is not replaced by `scripts/gen_gpio_defaults.py`
```
use gpio_defaults_block_0403 gpio_defaults_block_33
timestamp 1638492834
transform 1 0 8367 0 1 388400
box -38 0 6018 2224
use gpio_defaults_block  gpio_defaults_defaults_block_34
```
Will submit a PR soon.

NOTE: This effects all caravel chips! Previously taped out chips probably have the wrong `gpio_default_block` settings for gpio 34.

**Comment by RTimothyEdwards** [comment]
I have asked @jeffdi to merge the PR.
