### ISSUE TITLE
Caravan layout user power bus width

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel#461]
User power domains (vdda1/2, vssa1/2, vccd1/2, vssd1/2) busses should be 20um wide to meet the 5ohm maximum between pads per sky130 recommendations.

**Comment by mo-hosni** [comment]
Fixed for vdda1/vsssa1 which is the only power domain that has more than 1 pad per vdd/gnd. 
PR: https://github.com/efabless/caravel/pull/467
