### ISSUE TITLE
Use 4 center pins in the IC for the GND pins

### ISSUE THREAD

**Issue by mithro** [efabless/caravel#5]
Couldn't you use the center 4 balls for GND and then put a via in the middle of them through to the ground plane? It would get you back another 4 pins....

See this diagram for example;
![image](https://user-images.githubusercontent.com/21212/96062949-bbbd1800-0e4b-11eb-9432-aefaf74ad8b0.png)

**Comment by RTimothyEdwards** [comment]
Center pins are purposely left out so that we and users can make use of the space for inductors on the redistribution layer.

**Comment by RTimothyEdwards** [comment]
Also, blind vias cost more money than your standard minimalist PCB.

**Comment by RTimothyEdwards** [comment]
@mithro : Okay, got it now, after out conversation.  I still suggest gauging the interest in the analog community for using the redistribution layer for inductors (although in the same comment I would point out that if the user does not touch the redistribution layer, then there can potentially be only one mask ever made for it, which would reduce the cost of the bump bonding in the long run).

Also:  Note that I have most ground returns on separate nets for purposes of noise isolation.  The three ground domains that I have connected together are already tied to a single bump.  So by adding four additional pads in the middle, you can only gain one additional pin for the user.

**Comment by mithro** [comment]
> @mithro : Okay, got it now, after out conversation. I still suggest gauging the interest in the analog community for using the redistribution layer for inductors (although in the same comment I would point out that if the user does not touch the redistribution layer, then there can potentially be only one mask ever made for it, which would reduce the cost of the bump bonding in the long run).

This is expected. So basically, everyone would need to share that region.

**Comment by RTimothyEdwards** [comment]
@mithro :  This has been fixed in the documentation, and pushed.  I am waiting on some changes to the RTL from Mohamed Shalan's group before I add the additional user pin to the RTL.

**Comment by RTimothyEdwards** [comment]
User pin has been added to the RTL and all documentation (except for the provisional layout) has been updated, so I will close this ticket.
