### ISSUE TITLE
Makefile calls open_pdk configure with unrecognized option

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel#5]
Currently
```
./configure --enable-sky130-pdk=$(PDK_ROOT)/skywater-pdk/libraries --with-sky130-local-path=$(PDK_ROOT)
```
which gives the following and (tries to) installs in the default location instead
```
configure: WARNING: unrecognized options: --with-sky130-local-path
```

Should probably be
```
./configure --enable-sky130-pdk=$(PDK_ROOT)/skywater-pdk/libraries --prefix=$(PDK_ROOT)
```

See https://github.com/RTimothyEdwards/open_pdks/commit/44e7efa34a423fe26455860026602715a9b32744#diff-ecb3d5615afcbe1e5df55695252c8f0835e8cb1ec10a6048a83cf0a80d2a1ab3

**Comment by RTimothyEdwards** [comment]
This was changed at some point and the configure statement in the Makefile is currently correct, so I am closing this issue.
