### ISSUE TITLE
gpio_default_block not working for pins 0-4

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel#72]
From `caravel_user_project`
```
make gpio_defaults
```
gives
```
Traceback (most recent call last):
  File "/home/kanobailey/mpw-5/mpw-5d/caravel_user_project/caravel/scripts/gen_gpio_defaults.py", line 340, in <module>
    cellname = cellsused[int(gpioidx)]
ValueError: invalid literal for int() with base 10: '0\\[0\\]'
```
This is because the `mag` instances names for the first 5 `gpio_default_blocks` have changed.
```
use gpio_defaults_block  gpio_defaults_block_0\[0\]
use gpio_defaults_block  gpio_defaults_block_0\[1\]
use gpio_defaults_block  gpio_defaults_block_2\[0\]
use gpio_defaults_block  gpio_defaults_block_2\[1\]
use gpio_defaults_block  gpio_defaults_block_2\[2\]
```
Reverting these to the previous definitions
```
gpio_defaults_block_0
gpio_defaults_block_1
gpio_defaults_block_2
gpio_defaults_block_3
gpio_defaults_block_4
```
Allows the program to complete, but the blocks are not changed in `caravel.mag`.
This is because the program has been modified to skip the first 5 gpio_default_blocks.
```
    for i in range(5, 38):
        config_name = '`USER_CONFIG_GPIO_' + str(i) + '_INIT'
```
Reverting this to handle all 38 blocks corrects the problem.

Pull request will be submitted soon.

**Comment by RTimothyEdwards** [comment]
This has to be re-checked in light of a pull request that I made to fix the issue five days ago but which was not merged.  I changed the script to recognize the array names and map them to indexes.  That should fix this issue so the pull request should not be needed.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards I'll back out the changes related to `gpio_defaults_block`.
