### ISSUE TITLE
Delete master branch

### ISSUE THREAD

**Issue by mithro** [efabless/caravel#8]
https://github.com/efabless/caravel/tree/master -- It's empty

**Comment by mithro** [comment]
Lets delete for now, we can recreate it if we want.

**Comment by RTimothyEdwards** [comment]
@mithro :  I don't know how to remove a branch except locally;  I don't have a master branch in my local cloned copy.

**Comment by mithro** [comment]
Use the github interface? Or use `git push <remote> :master` -- Yes that `<nothing>`, `<semicolon>`, `master` -- The value for `<remote>` is most likely `origin` but should have a URL like `git+ssh://github.com/efabless/caravel.git`.

**Comment by RTimothyEdwards** [comment]
That worked, thanks for the info.
